# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o $ARTIFACT_DIR/output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: demo-contact-artifact-${{ github.run_id }}-${{ github.run_attempt }}
        path: $ARTIFACT_DIR/output

  publish:
    runs-on: self-hosted

    needs: build
    if: github.ref_name == 'main'
    
    steps:
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'ui/Sufi.Demo.PeopleDirectory.UI/Server/appsettings.json'
      env:
        ConnectionStrings.DefaultConnectionString: ${{ secrets.CONNECTIONSTRING }}
    - name: Publish to Services
      run: |
          dotnet publish "${{ github.workspace }}/$BUILD_PROJ" -c Release -o $DEPLOY_DIR
          systemctl restart $APP_NAME
